# Generated by Django 3.2.1 on 2021-05-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210504_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(help_text="Enter author's name", max_length=100, unique=True, verbose_name="Author's name"),
        ),
    ]
