# Generated by Django 3.2.1 on 2021-05-04 17:59

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=books.models.cover_path, verbose_name='Cover'),
        ),
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('epika', 'Epika'), ('lyrika', 'Lyrika'), ('drama', 'Drama')], default='image', max_length=6),
        ),
    ]
