# Generated by Django 3.2.1 on 2021-05-04 21:12

import books.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210504_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to=books.models.portrait_path, verbose_name='Portrait'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rate',
            field=models.FloatField(default=0, help_text='Please enter float value (range 0.0 - 5.0)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Rate'),
        ),
    ]
